services:
  app:
    build:
      context: ./docker/python
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
      - "8501:8501"
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pckeiba
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  db:
    image: postgres:15
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pckeiba
    ports:
      - "5433:5432"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.7.1
    ports:
      - "5000:5000"
    environment:
      # バックエンドDBはSQLite
      - MLFLOW_BACKEND_STORE_URI=sqlite:////mlflow_store/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow_store/artifacts
      - MLFLOW_HOST=0.0.0.0
    volumes:
      # 専用ディレクトリをマウント
      - ./mlflow_store:/mlflow_store
    command: mlflow server --backend-store-uri sqlite:////mlflow_store/mlflow.db --default-artifact-root /mlflow_store/artifacts --host 0.0.0.0

  frontend:
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./web:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --hostname 0.0.0.0"

volumes:
  frontend_node_modules:
