services:
  app:
    build:
      context: ./docker/python
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pckeiba
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    tty: true

  db:
    image: postgres:15
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pckeiba
    ports:
      - "5433:5432"
