exploration_results:
- logloss_top3: 0.556474480918579
  logloss_win: 0.22408764198721437
  n_samples: 73700
  temperature: 0.5
- logloss_top3: 0.49496496317884464
  logloss_win: 0.21902382086625083
  n_samples: 73700
  temperature: 0.75
- logloss_top3: 0.48017724539319073
  logloss_win: 0.22393042069976726
  n_samples: 73700
  temperature: 1.0
- logloss_top3: 0.4787324657136126
  logloss_win: 0.23008981844048063
  n_samples: 73700
  temperature: 1.25
- logloss_top3: 0.48156180610321825
  logloss_win: 0.23572891845071697
  n_samples: 73700
  temperature: 1.5
- logloss_top3: 0.48999388435922947
  logloss_win: 0.2446272199070952
  n_samples: 73700
  temperature: 2.0
generated_at: '2025-12-15T23:40:17.754939'
temperature: 0.75
